export const label = {
    appName: `Thinkly`,

    logIn: `Log In`,
    success: `Success`,
    logedInMessage: `You are logged in!`,
    cancel: `Cancel`,
    error: `Error`,
    userNotFoundAfterLogin: `No user found after login.`,
    enterEmailForPasswordReset: `Please enter your email address to reset your password.`,
    passwordResetMailSent: `Password reset email sent! Please check your inbox.`,
    ok: `OK`,
    email: `Email`,
    password: `Password`,
    signInWith: `Sign in with`,
    forgotPassword: `Forgot password?`,
    signUp: `Sign Up`,
    allFieldsRequire: `All fields are required.`,
    accountCreated: `Account created!`,
    signUpFailed: `Sign up failed`,
    name: `Name`,
    alreadyHaveAnAccount: `Already have an account?`,

    home: `Home`,
    overview: `Overview`,
    profile: `Profile`,

    back: `Back`,
    courseOverview: `Course Overview`,
    ongoing: `Ongoing`,
    completed: `Completed`,
    continue: `Continue`,
    start: `Start`,

    enterTopic: `Please enter a topic`,
    failedToSaveTopic: `Failed to save topic`,
    customCourse: `Custom\nCourse`,
    customCoursePlaceholder: `What do you want to learn about?`,
    createCourse: `Create Course`,
    creating: `Creating...`,

    correct: `Correct!`,
    tryAgain: `Try Again`,
    youEarned: `You earned`,
    theCorrectAnswerWas: `The correct answer was`,
    dayStreak: `day streak`,
    level: `Level`,
    yourCourses: `Your Courses`,
    createNewCourse: `Create New Course`,
    dailyChallenge: `Daily Challenge`,

    question: `Question`,
    incorrectAnswer: `Incorrect. Answer`,
    score: `Score`,
    loading: `Loading...`,
    completeLesson: `Complete Lesson`,
    next: `Next`,
    congratulations: `Congratulations!`,
    lessonComplete: `Lesson Complete!`,

    subscriptionStatus: `Subscription Status`,
    stripPayment: `Strip Payment`,
    yourPlanActivated: `Your premium plan is activated.`,
    premiumPlan: `Premium Plan`,
    month: `month`,
    unlimitedCourses: `Unlimited courses`,
    premiumBadges: `Premium badges`,
    processing: `Processing...`,
    payWith: `Pay with`,

    imagePickerError: `Image picker error`,
    avatarUpdated: `Avatar updated (local only)!`,
    failedToUpdateAvatar: `Failed to update avatar.`,
    badges: `Badges`,
    noCourses: `No courses yet.`,
    preferences: `Preferences`,
    notifications: `Notifications`,
    theme: `Theme`,
    language: `Language`,
    logOut: `Log Out`,

    settings: `Settings`,
    permissionRequired: `Permission required`,
    permissionRequiredDesc: `Please enable notifications in settings`,
    darkMode: `Dark Mode`,
    dailyReminders: `Daily Reminders`,
    changeReminderTime: `Change Reminder Time`,
    done: `Done`,
    sendTestNotification: `Send Test Notification`,

    courseLimitReached: `Course Limit Reached`,
    subscribeTo: `Subscribe to create unlimited courses`,
    subscribe: `Subscribe`,
    whatDoYouWantToLearn: `What do you want to learn?`,
    investing: `Investing`,
    mentalHealth: `Mental Health`,
    relationships: `Relationships`,
    other: `Other`,

    ongoingCourseLimitReached: `Ongoing Course Limit Reached`,
    ongoingCourseLimitReachedDesc: `You can have up to 3 ongoing courses at a time. To start a new one, please complete one of your current courses first.`,

    no: `No`,
    yes: `Yes`,
    removeCourse: `Remove Course`,
    removeCourseDesc: `Are you sure, you want to remove`,
    course: `course`,

    yourBadges: `Your Badges`,
    yourBadgesDesc: `Earn badges as you learn, complete courses and stay consistent:`,
    totalBadges: `Total Badges:`,
    badgesObject: {
        firstLesson: {
            title: `First Lesson`,
            desc: `Complete your\nfirst lesson`,
        },
        streakStarter: {
            title: `Streak Starter`,
            desc: `Maintain a 3-day\nlearning streak`,
        },
        superLearner: {
            title: `Super Learner`,
            desc: `Finish 5\nfull courses`,
        },
        curiousMind: {
            title: `Curious Mind`,
            desc: `Create 3 custom\ncourses`,
        },
        dedicated: {
            title: `Dedicated`,
            desc: `7-day learning\nstreak`,
        },
        weekOne: {
            title: `Week One`,
            desc: `Finish your\nfirst week`,
        },
    },

    unsubscribePlan: `Unsubscribe Current Plan`,
    unsubscribePlanTitle: `Unsubscribe Plan`,
    unsubscribePlanDesc: `Are you sure you want to unsubscribe current plan.`,
    unsubscribePlanSuccess: `Your subscription will be canceled at the end of the billing period.`,
    unsubscribePlanFailed: `Failed to cancel subscription.`,

    allLessonsAreFinished: `All lessons are finished!`,
    congratulationsYouEarnedNewBadge: `Congratulations! You've earned a new badge!`,

    courseGenerationMessages: {
        short: [
            `Preparing your personalized learning journey…`,
            `Please wait 20-30 seconds, your new learning journey will be ready shortly!`,
            `Don't worry, while you wait, you're becoming wiser in the future!`,
            `We're just spending a few seconds thinking big thoughts…`,
            `We're assembling your personalized course, it'll only take a moment.`,
            `Big ideas are brewing, this will only take a moment!`,
            `We're crafting your course with care, almost there!`,
            `Assembling your unique learning path, stay tuned!`,
            `Your course is almost ready, great things take a little time.`,
        ],
        medium: [
            `Preparing your personalized learning journey…`,
            `Please wait 1-1.5 minutes, your new learning journey will be ready shortly!`,
            `Don't worry, while you wait, you're becoming wiser in the future!`,
            `We're just spending a few seconds thinking big thoughts…`,
            `We're assembling your personalized course, it'll only take a moment.`,
            `Big ideas are brewing, this will only take a moment!`,
            `We're crafting your course with care, almost there!`,
            `Assembling your unique learning path, stay tuned!`,
            `Your course is almost ready, great things take a little time.`,
        ],
    },

    congratulationsLevelUp: `You've reached a new level - you're getting smarter and smarter!`,
    courseType: `Course Type`,
    short: `Short`,
    medium: `Medium`,
    long: `Long`,

    noCourse: `There are currently no courses in your list.`,

    courseLength: [
        {
            title: `Short`,
            desc: `4 lessons`,
            key: `short`,
        },
        {
            title: `Medium`,
            desc: `6 lessons`,
            key: `medium`,
        },
    ],
}